ChilliSoftAssessmentMeetingMinuteTakerMVC/Controllers/MeetingController.cs
using ChilliSoftAssessmentMeetingMinuteTakerDLL.DomainModels;
using ChilliSoftAssessmentMeetingMinuteTakerDLL.Dtos;
using ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels;
using ChilliSoftAssessmentMeetingMinuteTakerMVC.Hubs;
using GenericBaseMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace ChilliSoftAssessmentMeetingMinuteTakerMVC.Controllers;

[Authorize]
public class MeetingController : Controller
{
    public IHubContext<MeetingHub> _hub { get; set; }
    public MeetingController(IHubContext<MeetingHub> hub)
    {
        _hub = hub;
    }


    public async Task<MeetingViewModel> AssembleMeetingModel(int meetingId) {
        int MeetingId;

        if (meetingId < 1)
        {
            MeetingId = 0;
        }
        else
        {

            MeetingId = meetingId;
        }
        #region FetchFromAPI

        var model = new MeetingViewModel();
        var Users = await UserService.GetAll();
        var AllMessages = await MeetingMinutesService.GetAll();
        var AllMeetingItems = await MeetingItemService.GetAll();
        var AllMeetings = await MeetingService.GetAll();
        var AllStatuses = await MeetingItemService.GetAllStatuses();
        var AllTypes = await MeetingService.GetAllTypes();


        #endregion

        #region MessageDToToVM
        var MessageVMs = new List<MeetingMessageViewModel>();
        foreach (var item in AllMessages)
        {
            var entity = new MeetingMessageViewModel()
            {
                Message = item.Message,
                CreationDateTime = item.CreationDateTime,
                ItemId = item.ItemId,
                SenderId = item.CreatorId,
                MeetingId = item.MeetingId,
                CreatorId = item.UserId,
                Id = item.Id
            };
            MessageVMs.Add(entity);
        }

        #endregion

        #region MeetingDToToVM

        var MeetingVMs = new List<MeetingHeaderViewModel>();
        foreach (var item in AllMeetings)
        {
            var entity = new MeetingHeaderViewModel()
            {
                MeetingName = item.MeetingName,
                CreationDateTime = item.CreationDateTime,
                CreatorId = item.CreatorId,
                MeetingStatus = item.MeetingStatus,
                MeetingTypeId = item.MeetingTypeId,
                Id = item.Id,
                AllTypes = AllTypes
            };
            MeetingVMs.Add(entity);
        }

        #endregion
        var currentMeeting = MeetingVMs.FirstOrDefault(m => m.Id == MeetingId);
        if (currentMeeting == null) { 
            currentMeeting = new MeetingHeaderViewModel(); 
        if (AllMeetingItems.Count > 0 ) { currentMeeting.MeetingTypeId = AllMeetingItems.First().MeetingId; }
        }

        #region ItemDToToVM
        var ItemVMs = new List<MeetingItemVeiwModel>();
        foreach (var item in AllMeetingItems)
        {
            var entity = new MeetingItemVeiwModel()
            {
                ItemName = item.ItemName,
                CreationDateTime = item.CreationDateTime,
                StatusId = item.StatusId,
                Comment = item.Comment,
                CreatorId = item.CreatorId,
                MeetingId = item.MeetingId,
                UserId = item.UserId,
                Id = item.Id,
                Statuses = AllStatuses,
                CurrentMeetingTypeId = currentMeeting.MeetingTypeId,
                MeetingType = item.MeetingType
            };
            ItemVMs.Add(entity);
        }

        #endregion
        var MyProfile = Users.FirstOrDefault(m => m.UserEmail == User.Identity.Name);

        var newMessage = new SendMeetingMessageViewModel()
        {
            SenderId = MyProfile.Id,
            MeetingId = MeetingId
        };

        model.MeetingId = MeetingId;
        model.newMeeting = new CreateMeetingViewModel() { MeetingTypes = AllTypes };
        model.newItem = new CreateMeetingItemViewModel() { Meetings = MeetingVMs, Statuses = AllStatuses };
        model.NewMessage = newMessage;
        model.OtherMeetings = MeetingVMs;
        model.Messages = MessageVMs;
        model.Items = ItemVMs;
        model.MeetingName = currentMeeting.MeetingName;
        model.MeetingTypeId = currentMeeting.MeetingTypeId;

        return(model);
    }

    // GET: MeetingController
    public async Task<ActionResult> Index()
    {
        var model = await AssembleMeetingModel(0);

        return View(model);
    }
    public async Task<IActionResult> AttendMeeting(string Id)
    {

        var model = await AssembleMeetingModel(Convert.ToInt32(Id));

        return View("Index", model);
    }

    [HttpPost]
    public async Task<IActionResult> SendMeetingMessage(SendMeetingMessageViewModel model) {

        await MeetingMinutesService.Create(model);

        var SRMessage = new SignalRMessage() { 
        Message = model.Message,
        UserId = model.SenderId,
        ItemId = model.ItemId,
        MeetingId = model.MeetingId
        };

        await SendAMessage(SRMessage);

        return RedirectToAction("AttendMeeting",model.MeetingId);
    }

    public async Task<IActionResult> SendAMessage(SignalRMessage Message) {
        await _hub.Clients.All.SendAsync("RecieveMessage",Message);
        return View();
    }

    public IActionResult OnGoingMeeting() {

        return View();
    }

    public async Task<IActionResult> CreateNewMeeting(CreateMeetingViewModel newMeeting) {
        var Users =  await UserService.GetAll();
        var MyProfile = Users.FirstOrDefault(m => m.UserEmail == User.Identity.Name);
        newMeeting.CreatorId = MyProfile.Id;
        MeetingService.Create(newMeeting);

        var SRMessage = new SignalRMessage()
        {
            Code = 101
        };

        await SendAMessage(SRMessage);

        return RedirectToAction("Index");
    }


}

ChilliSoftAssessmentMeetingMinuteTakerMVC/Controllers/MeetingItemController.cs
using ChilliSoftAssessmentMeetingMinuteTakerDLL.DomainModels;
using ChilliSoftAssessmentMeetingMinuteTakerDLL.Dtos;
using ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels;
using ChilliSoftAssessmentMeetingMinuteTakerMVC.Hubs;
using GenericBaseMVC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace ChilliSoftAssessmentMeetingMinuteTakerMVC.Controllers
{
    public class MeetingItemController : Controller
    {
        public IHubContext<MeetingHub> _hub { get; set; }
        public MeetingItemController(IHubContext<MeetingHub> hub)
        {
            _hub = hub;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SendAMessage(SignalRMessage Message)
        {
            await _hub.Clients.All.SendAsync("RecieveMessage", Message);
            return View();
        }

        public async Task<IActionResult> UpdateItem(CreateMeetingItemViewModel model)
        {
            var Users = await UserService.GetAll();
            var MyProfile = Users.FirstOrDefault(m => m.UserEmail == User.Identity.Name);

            var dto = new CreateItemDto()
            {
                CreatorId = MyProfile.Id,
                ItemName = model.ItemName,
                Comment = model.Comment,
                StatusId = model.StatusId,
                MeetingId = model.MeetingId,
                Id = model.Id
            };

            await MeetingItemService.Update(dto);

            return RedirectToAction("Index", controllerName: "Meeting");

        }
            public async Task< IActionResult> CreateNewItem(CreateMeetingItemViewModel model) {
            var Users = await UserService.GetAll();
            var AllMeetings = await MeetingService.GetAll();
            var MyProfile = Users.FirstOrDefault(m => m.UserEmail == User.Identity.Name);

            var dto = new CreateItemDto() { 
            CreatorId =MyProfile.Id ,
            ItemName = model.ItemName,
            Comment = model.Comment,
            StatusId = model.StatusId,
            MeetingId =model.MeetingId ,
            MeetingType = AllMeetings.FirstOrDefault(m=>m.Id==model.MeetingId).MeetingTypeId
            };

            await MeetingItemService.Create(dto);
            var SRMessage = new SignalRMessage()
            {
                Code = 102
            };

            await SendAMessage(SRMessage);
            return RedirectToAction("Index",controllerName:"Meeting");
        }
    }
}

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChilliSoftAssessmentMeetingMinuteTakerMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChilliSoftAssessmentMeetingMinuteTakerMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/fontawesome.min.js" integrity="sha512-nKvEIGRKw2OQCR34yLfnWnvrOBxidLG9aK+vzsBxCZ/9ZxgcS4FrYcN+auWUTkCitTVZAt82InDKJ7x+QtKu6g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Meeting Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link  dropdown-toggle" href="#" id="navbarDropdown4" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Meeting
                            </a>
                            <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown4">
                                <li class="nav-item dropdown-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="Index"><i class="fa-solid fa-handshake"></i>Meetings</a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ChilliSoftAssessmentMeetingMinuteTakerMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/aspnet/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_Meeting.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingViewModel



<div id="meeting">
    <div id="meetingBody" class="card mx-auto" style="max-width:400px">
       
        <div class="card-header bg-transparent">
            <div class="navbar navbar-expand p-0">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                                <div class="position-relative avatar">
                                <img class="img-fluid rounded-circle" src="profileimage.png" />
                                <span class="position-absolute bottom-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
                                <span class="visually-hidden">new alerts</span>
                                 </span>
                                </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            @Model.MeetingName
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <i class="fas fa-phone-alt"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <i class="fas fa-video"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <i class="fas fa-times"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="MeetingChatBody" class="card-body p-4" style="height:500px;overflow:auto;">

             @foreach (var item in Model.Messages.Where(m=>m.MeetingId==Model.MeetingId))
            {
                <partial name="_meetingMessage" model="item"/>
                
            }

        </div>

        <div class="card-footer bg-transparent position-absolute bottom-0 w-100 m0 p-1">
            <partial name="_sendMeetingMessage" model="Model.NewMessage" />
        </div>

    </div>
</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_MeetingItemsControl.cshtml
@model List<ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingItemVeiwModel>

<div id="meeting">
    <div id="meetingBody" class="card mx-auto" style="max-width:400px">

        <div class="card-header bg-transparent">
            <div class="navbar navbar-expand p-0">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            Meeting Items
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <i class="fas fa-plus"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="card-body p-4" style="height:500px;overflow:auto;">
            
            @foreach (var item in Model)
            {
                @if (item.CurrentMeetingTypeId == item.MeetingType)
                {
                    
            <partial name="_meetingItemHeader" model="item"/>
                }
                
            }
            
            
            <div class="d-flex align-items-baseline mb-4">
                <div class="pe-2 w-100">
                    <a href="#!" class="nav-link">
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
                @*text-end justify-content-end*@
            </div>
        </div>

        <div class="card-footer bg-transparent position-absolute bottom-0 w-100 m0 p-1">
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ItemModal">
                <i class="fas fa-plus"></i>
            </button>
        </div>

    </div>
</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_MeetingsControl.cshtml
@model List<ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingHeaderViewModel>

<div id="meeting">
    <div id="meetingBody" class="card mx-auto" style="max-width:400px">

        <div class="card-header bg-transparent">
            <div class="navbar navbar-expand p-0">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            Meetings
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <i class="fas fa-plus"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="card-body p-4" style="height:500px;overflow:auto;">
            @foreach (var item in Model)
            {
            <partial name="_meetingHeader" model="item" />
                
            }

            <div class="d-flex align-items-baseline mb-4">
                <div class="pe-2 w-100 position-absolute bottom-1">
                    <a href="#!" class="nav-link">
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
                @*text-end justify-content-end*@
            </div>

        </div>

        <div class="card-footer bg-transparent position-absolute bottom-0 w-100 m0 p-1">
            <button class="btn btn-primary" data-bs-toggle="modal"data-bs-target="#MeetingModal">
                <i class="fas fa-plus"></i>
           </button>
        </div>

    </div>
</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_UpdateMeetingItem.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.CreateMeetingItemViewModel


<form asp-action="UpdateItem" asp-controller="MeetingItem">
   
    <div id="UpdateItemModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Update Meeting Item</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Item Name</label>
                        <input asp-for="ItemName" id="UpdateItemName" type="text" class="form-control">
                        <input asp-for="Id" id="UpdateItemId" hidden type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Comment</label>
                        <input asp-for="Comment" id="UpdateComment" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <select asp-for="MeetingId" style="width:90%">
                            @foreach (var item in Model.Meetings)
                            {
                                @if (Model.MeetingId == item.Id)
                                {
                                    <option selected value="@item.Id">@item.MeetingName</option>
                                }
                                else
                                {

                                    <option value="@item.Id">@item.MeetingName</option>
                                }
                               
                            }

                        </select>
                    </div>

                    <div class="form-group">
                        <select asp-for="StatusId" style="width:90%">
                            @foreach (var item in Model.Statuses)
                            {
                                @if (Model.StatusId == item.Id)
                                {
                                    <option selected value="@item.Id">@item.StatusName</option>
                                }
                                else
                                {
                                    
                                <option value="@item.Id">@item.StatusName</option>
                                }
                            }
                        </select>
                    </div>

                </div>
                <div class="modal-footer">
                    <button id="CreateMeetingItem" type="submit" class="btn btn-primary">Update</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    $("#CreateMeetingItem").click(function () {
        console.log("Created");
    });
</script>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_meetingHeader.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingHeaderViewModel
@{
    int typeId = Model.MeetingTypeId;
    Model.MeetingType = Model.AllTypes.FirstOrDefault(m => m.Id == typeId).MeetingTypeName;
}

<div class="d-flex align-items-baseline mb-4 ">
    <div class="pe-2 w-100 ">
        <div class="card card-text p-2 px-3 m-1 MeetingOption">
    <input hidden class="MeetingHeadId" value="@Model.Id" />
          @Model.MeetingName
            <div class="small ">
                @Model.MeetingType
            </div>
        </div>
    </div>
    @*text-end justify-content-end*@
</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_meetingItemHeader.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingItemVeiwModel
@{
    int statusId = Model.StatusId;
    Model.Status = Model.Statuses.FirstOrDefault(m=>m.Id==statusId).StatusName;
}

<div class="d-flex align-items-baseline mb-4 ">
    <div class="pe-2 w-100 row ">
        <div class="card card-text p-2 px-3 m-1 MeetingItemOption ">
             <input hidden class="MeetingItemHeadId" value="@Model.Id" />
            <div class="col-8 ">

            @Model.ItemName
        <div class="small ">
            @Model.Comment
            @Model.Status
        </div>
            </div>
        </div>
        <div class="col-4">
            <button id="UpdateItemButton" class="btn btn-light UpdateItemButton" data-bs-toggle="modal" data-bs-target="#UpdateItemModal">
            <i class="fas fa-pencil"></i>
                <input hidden class="ItemId" value="@Model.Id"/>
                <input hidden class="ItemName" value="@Model.ItemName" />
                <input hidden class="ItemComment" value="@Model.Comment" />
                <input hidden class="ItemStatus" value="@Model.StatusId" />
        </button>
        </div>
    </div>
    @*text-end justify-content-end*@

</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_meetingItemModal.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.CreateMeetingItemViewModel


<form asp-action="CreateNewItem" asp-controller="MeetingItem"> 

<div id="ItemModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Meeting Item</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Item Name</label>
                    <input asp-for="ItemName" id="lat" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Comment</label>
                    <input asp-for="Comment" id="lon" type="text" class="form-control">
                </div>
                <div class="form-group">
                        <select asp-for="MeetingId" style="width:90%">
                            @foreach (var item in Model.Meetings)
                            {
                                
                            <option value="@item.Id">@item.MeetingName</option>
                            }
    
                        </select>
                </div>

                    <div class="form-group">
                        <select asp-for="StatusId" style="width:90%">
                            @foreach (var item in Model.Statuses)
                            {

                                <option value="@item.Id">@item.StatusName</option>
                            }
                        </select>
                    </div>

            </div>
            <div class="modal-footer">
                <button id="CreateMeetingItem" type="submit" class="btn btn-primary">Create</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</form>

<script type="text/javascript">
    $("#CreateMeetingItem").click(function () {
        console.log("Created");
    });
</script>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_meetingMessage.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.MeetingMessageViewModel


<div class="d-flex align-items-baseline mb-4">
    
    <div class="position-relative avatar">
        <img class="img-fluid rounded-circle" src="profileimage.png" />
        <span class="position-absolute bottom-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
    <span class="visually-hidden">new alerts</span>
        </span>
    </div>

    <div class="pe-2">
        <div class="card card-text d-inline-block p-2 px-3 m-1">
            @Model.Message
        </div>
        <div class="small">
            @Model.CreationDateTime
        </div>
    </div>
    @*text-end justify-content-end*@

</div>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_meetingModal.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.CreateMeetingViewModel


<form asp-action="CreateNewMeeting" asp-controller="Meeting">
<div id="MeetingModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Meeting</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label class="col-form-label">Meeting Name</label>
                        <input asp-for="MeetingName" id="Name" type="text" class="form-control">
                </div>

                    <div class="form-group">
                        <select asp-for="MeetingTypeId" style="width:90%">
                            @foreach (var item in Model.MeetingTypes)
                            {
                                
                            <option value="@item.Id">@item.MeetingTypeName</option>
                            }

                        </select>
                    </div>

            </div>
            <div class="modal-footer">
                    <button id="CreateMeetingForm" type="submit" class="btn btn-primary">Create</button>

                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
                </div>
        </div> @*type="submit"data-bs-save="modal"*@
    </div>
</form>

<script type="text/javascript">
    $("#CreateMeeting").click(function () {
        console.log("Created");
        $(location).attr('href', 'https://google.com');
    });
</script>

ChilliSoftAssessmentMeetingMinuteTakerMVC/Views/Shared/_sendMeetingMessage.cshtml
@model ChilliSoftAssessmentMeetingMinuteTakerDLL.ViewModels.SendMeetingMessageViewModel

<form asp-action="SendMeetingMessage" asp-controller="Meeting" >
    <input asp-for="SenderId" hidden class="form-control" />
    <input asp-for="ItemId" id="SendMessageItemId" hidden class="form-control" />
    <input asp-for="MeetingId" id="SendMessageMeetingId" hidden class="form-control" />
<div class="input-group">
      
    <div class="input-group-text bg-transparent border-0">
        <button id="SendAttatchment" class="btn btn-light">
            <i class="fas fa-paperclip"></i>
        </button>
    </div>
    <input asp-for="Message" type="text" class="form-control border-0" placeholder="Write a message..." />
    <div class="input-group-text bg-transparent border-0">
        <button class="btn btn-light">
            <i class="fas fa-smile"></i>
        </button>
    </div>
    <div class="input-group-text bg-transparent border-0">
        <button type="submit" class="btn btn-light">
            <i class="fas fa-paper-plane"></i>
        </button>
    </div>
</div>
</form>